version: '3'
services:
 strapi:
   image: customstrapi:1.0
   container_name: strapi
   environment:
     DATABASE_CLIENT: mysql
     DATABASE_HOST: mysql
     DATABASE_PORT: 3306
     DATABASE_NAME: strapi
     DATABASE_USERNAME: strapi
     DATABASE_PASSWORD: strapi
     DATABASE_SSL: 'false'
     VIRTUAL_PORT: 1337
     VIRTUAL_HOST: test.matportfolio.ovh
   volumes:
     # - ./strapi/config:/opt/app/config
     - ./strapi/src/uploads:/opt/app/src/uploads
     # - ./strapi/package.json:/opt/package.json
     # - ./strapi/.env:/opt/app/.env
   ports:
     - '1337:1337'
   networks:
     - back-network
   depends_on:
     - mysql

 mysql:
   image: mysql
   command: mysqld --default-authentication-plugin=mysql_native_password
   volumes:
     - ./data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: strapi
     MYSQL_DATABASE: strapi
     MYSQL_USER: strapi
     MYSQL_PASSWORD: strapi
   networks:
     - back-network

networks:
 back-network:
   name: back-network
   driver: bridge
       
 
